version: '3.3'
services:
  web:
    image: nginx:1.16
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:${HOST_IP}'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/cache/:/var/cache/nginx/
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
  redis:
    image: redis:6
    ports:
      - 6379:6379
